// make_linux_status_icons.swift — icon trạng thái bộ gõ Linux (Fcitx5 tray / IBus panel):
// viettelex = Vᴛ (Tiếng Việt, như MenuIcon.pdf của macOS), viettelex-off = E (English, như
// logo EN phím cách iOS SpaceLogoEN). CÙNG hình học với make_space_logo.swift / make_icon.swift:
// hộp vuông bo góc (bán kính 0,28 cạnh) viền 1/16, chữ đặc cao 0,53 hộp, căn giữa.
// Xuất SVG vector (đường glyph từ CoreText): bản thường màu #888888 (đọc được trên panel
// sáng lẫn tối) + bản -symbolic #2e3436 (GNOME/KDE tự tô màu theo theme).
//
// Usage: swift Scripts/make_linux_status_icons.swift        (chạy từ gốc repo)
import AppKit
import CoreText

func glyphPath(_ ch: Character, weight: NSFont.Weight, size: CGFloat,
               baselineY: CGFloat, leftX: CGFloat) -> (path: CGPath, width: CGFloat)? {
    let font = NSFont.systemFont(ofSize: size, weight: weight) as CTFont
    var chars = [UniChar](String(ch).utf16)
    var glyph = CGGlyph()
    guard CTFontGetGlyphsForCharacters(font, &chars, &glyph, 1) else { return nil }
    var bbox = CGRect.zero
    withUnsafeMutablePointer(to: &glyph) { g in
        bbox = CTFontGetBoundingRectsForGlyphs(font, .default, g, nil, 1)
    }
    var transform = CGAffineTransform(translationX: leftX - bbox.minX, y: baselineY)
    guard let path = CTFontCreatePathForGlyph(font, glyph, &transform) else { return nil }
    return (path, bbox.width)
}

func f(_ v: CGFloat) -> String {
    var s = String(format: "%.4f", Double(v))
    while s.hasSuffix("0") { s.removeLast() }
    if s.hasSuffix(".") { s.removeLast() }
    return s == "-0" ? "0" : s
}

func svgPath(_ p: CGPath) -> String {
    var d = ""
    p.applyWithBlock { el in
        let e = el.pointee, pts = e.points
        switch e.type {
        case .moveToPoint: d += "M\(f(pts[0].x)) \(f(pts[0].y))"
        case .addLineToPoint: d += "L\(f(pts[0].x)) \(f(pts[0].y))"
        case .addQuadCurveToPoint: d += "Q\(f(pts[0].x)) \(f(pts[0].y)) \(f(pts[1].x)) \(f(pts[1].y))"
        case .addCurveToPoint:
            d += "C\(f(pts[0].x)) \(f(pts[0].y)) \(f(pts[1].x)) \(f(pts[1].y)) \(f(pts[2].x)) \(f(pts[2].y))"
        case .closeSubpath: d += "Z"
        @unknown default: break
        }
    }
    return d
}

/// Cùng phép dựng với make_space_logo.swift `draw` (đơn vị S = 16).
func svg(main: Character, sub: Character?, color: String) -> String? {
    let S: CGFloat = 16
    let borderWidth: CGFloat = 1.0
    let box = CGRect(x: borderWidth / 2, y: borderWidth / 2, width: S - borderWidth, height: S - borderWidth)
    let radius = box.height * 0.28
    guard let vProbe = glyphPath("V", weight: .bold, size: 20, baselineY: 0, leftX: 0) else { return nil }
    let capPerPt = vProbe.path.boundingBox.height / 20
    let mSize = S * 0.53 / capPerPt
    let tSize = mSize * 0.4
    let gap = -mSize * 0.05
    guard let mW = glyphPath(main, weight: .bold, size: mSize, baselineY: 0, leftX: 0) else { return nil }
    let tW = sub.flatMap { glyphPath($0, weight: .black, size: tSize, baselineY: 0, leftX: 0) }
    let totalW = mW.width + (tW.map { gap + $0.width } ?? 0)
    let baselineY = box.minY + (box.height - mW.path.boundingBox.height) / 2
    let leftX = box.minX + (box.width - totalW) / 2
    guard let m = glyphPath(main, weight: .bold, size: mSize, baselineY: baselineY, leftX: leftX) else { return nil }
    let t = sub.flatMap { glyphPath($0, weight: .black, size: tSize, baselineY: baselineY,
                                    leftX: leftX + m.width + gap) }
    let name = sub == nil ? "E (English) — logo EN phím cách iOS" : "Vᴛ (Tiếng Việt) — MenuIcon.pdf macOS"
    var out = """
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- VietTelex status icon \(name). GENERATED by Scripts/make_linux_status_icons.swift — do not edit. -->
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
     <g transform="matrix(1 0 0 -1 0 16)">
      <rect x="\(f(box.minX))" y="\(f(box.minY))" width="\(f(box.width))" height="\(f(box.height))" rx="\(f(radius))" ry="\(f(radius))" fill="none" stroke="\(color)" stroke-width="\(f(borderWidth))"/>
      <path d="\(svgPath(m.path))" fill="\(color)"/>

    """
    if let t {
        out += "  <path d=\"\(svgPath(t.path))\" fill=\"\(color)\" stroke=\"\(color)\" stroke-width=\"\(f(tSize * 0.06))\" stroke-linejoin=\"round\"/>\n"
    }
    out += " </g>\n</svg>\n"
    return out
}

let root = CommandLine.arguments.count > 1 ? CommandLine.arguments[1] : "."
let dir = "\(root)/linux/packaging/data/icons/hicolor/scalable/status"
for (name, main, sub) in [("viettelex", Character("V"), Character("T") as Character?),
                          ("viettelex-off", Character("E"), nil)] {
    for (suffix, color) in [("", "#888888"), ("-symbolic", "#2e3436")] {
        guard let s = svg(main: main, sub: sub, color: color) else { fatalError("glyph \(main)") }
        let path = "\(dir)/\(name)\(suffix).svg"
        try! s.write(toFile: path, atomically: true, encoding: .utf8)
        print("wrote \(path)")
    }
}
