#!/usr/bin/env python3
"""Generate windows/engine/src/unicode_tables.hpp from Python's unicodedata.

Tables for the text tools (text_tools.cpp): general-category classes, full case mapping
(str.upper / str.lower = Unicode SpecialCasing, unconditional, root locale — the same
mapping Swift uppercased()/lowercased() and Kotlin uppercase()/lowercase() use), canonical
decomposition (NFD), canonical combining classes and primary composites (NFC).

    python3 windows/engine/tools/gen_unicode.py      # rewrites src/unicode_tables.hpp

Deterministic: output depends only on the Python unicodedata version (printed in the header).
"""
import os
import sys
import unicodedata as ud

MAX = 0x110000
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "unicode_tables.hpp")
SAMPLE = os.path.join(HERE, "..", "tests", "unicode-sample.txt")

# Character classes (text_tools.cpp CharClass): 0 other, 1 cased letter (Lu Ll Lt),
# 2 other letter (Lm Lo), 3 mark (Mn Mc Me), 4 decimal digit (Nd), 5 case-ignorable
# non-letter (Cf Sk — for the Final_Sigma context).
def cls(cp):
    c = ud.category(chr(cp))
    if c in ("Lu", "Ll", "Lt"):
        return 1
    if c in ("Lm", "Lo"):
        return 2
    if c in ("Mn", "Mc", "Me"):
        return 3
    if c == "Nd":
        return 4
    if c in ("Cf", "Sk"):
        return 5
    return 0


def ranges():
    out = []
    prev = None
    for cp in range(MAX):
        if 0xD800 <= cp <= 0xDFFF:
            c = 0
        else:
            c = cls(cp)
        if c != prev:
            out.append((cp, c))
            prev = c
    return out


def mapping(fn):
    rows, pool = [], []
    for cp in range(MAX):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        s = fn(chr(cp))
        if s != chr(cp):
            rows.append((cp, len(pool), len(s)))
            pool.extend(ord(x) for x in s)
    return rows, pool


def is_hangul_syllable(cp):
    return 0xAC00 <= cp <= 0xD7A3


def decomp():
    rows, pool = [], []
    for cp in range(MAX):
        if 0xD800 <= cp <= 0xDFFF or is_hangul_syllable(cp):
            continue  # Hangul is algorithmic
        s = ud.normalize("NFD", chr(cp))
        if s != chr(cp):
            rows.append((cp, len(pool), len(s)))
            pool.extend(ord(x) for x in s)
    return rows, pool


def ccc():
    out = []
    for cp in range(MAX):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c = ud.combining(chr(cp))
        if c:
            out.append((cp, c))
    return out


def composites():
    pairs = []
    for cp in range(MAX):
        if 0xD800 <= cp <= 0xDFFF or is_hangul_syllable(cp):
            continue
        d = ud.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        parts = [int(x, 16) for x in d.split()]
        if len(parts) != 2:
            continue
        # primary composite = canonical pair decomposition not excluded from composition
        if ud.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
            pairs.append((parts[0], parts[1], cp))
    pairs.sort()
    return pairs


def emit_u32(f, name, values, per=12):
    f.write(f"constexpr uint32_t {name}[{len(values)}] = {{\n")
    for i in range(0, len(values), per):
        f.write("  " + ",".join(f"0x{v:X}" for v in values[i:i + per]) + ",\n")
    f.write("};\n\n")


def main():
    rg = ranges()
    up_rows, up_pool = mapping(str.upper)
    lo_rows, lo_pool = mapping(str.lower)
    de_rows, de_pool = decomp()
    cc = ccc()
    comp = composites()
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// GENERATED by windows/engine/tools/gen_unicode.py — do not edit.\n")
        f.write(f"// Unicode {ud.unidata_version} (Python unicodedata).\n")
        f.write("#pragma once\n#include <cstdint>\n\nnamespace vtx { namespace uni {\n\n")
        # class ranges: start << 3 | class
        emit_u32(f, "kClassRanges", [s << 3 | c for s, c in rg])
        for nm, rows, pool in (("Upper", up_rows, up_pool), ("Lower", lo_rows, lo_pool),
                               ("Decomp", de_rows, de_pool)):
            # row: cp (21 bits) << 11 ... keep it simple: three parallel arrays
            emit_u32(f, f"k{nm}Cp", [r[0] for r in rows])
            emit_u32(f, f"k{nm}Off", [r[1] << 3 | r[2] for r in rows])
            emit_u32(f, f"k{nm}Pool", pool)
        emit_u32(f, "kCccCp", [c[0] for c in cc])
        f.write(f"constexpr uint8_t kCccVal[{len(cc)}] = {{\n")
        for i in range(0, len(cc), 24):
            f.write("  " + ",".join(str(c[1]) for c in cc[i:i + 24]) + ",\n")
        f.write("};\n\n")
        # composition: key = first << 21 | second (both < 2^21) as uint64
        f.write(f"constexpr uint64_t kCompKey[{len(comp)}] = {{\n")
        for i in range(0, len(comp), 8):
            f.write("  " + ",".join(f"0x{(a << 21 | b):X}ull" for a, b, _ in comp[i:i + 8]) + ",\n")
        f.write("};\n\n")
        emit_u32(f, "kCompVal", [c for _, _, c in comp])
        f.write("}}  // namespace vtx::uni\n")
    print(f"wrote {OUT}: {len(rg)} class ranges, upper {len(up_rows)}, lower {len(lo_rows)}, "
          f"decomp {len(de_rows)}, ccc {len(cc)}, composites {len(comp)} (Unicode {ud.unidata_version})",
          file=sys.stderr)


def sample():
    """Cross-check fixture for tests/text_tests.cpp: random strings (fixed seed) from the
    ranges that matter, with Python's NFC / NFD / upper / lower as the expected values."""
    import random
    rnd = random.Random(20260928)
    pools = [range(0x20, 0x7F), range(0xC0, 0x250), range(0x300, 0x370), range(0x370, 0x400),
             range(0x400, 0x530), range(0x1E00, 0x1F00), range(0x1F00, 0x2000), range(0x1100, 0x1200),
             range(0xAC00, 0xAC80), range(0x0590, 0x0700), range(0x0900, 0x0980), range(0xFB00, 0xFB50),
             range(0x1F600, 0x1F650), range(0x10400, 0x10450)]
    viet = "aăâeêioôơuưyđ"
    marks = [0x300, 0x301, 0x303, 0x309, 0x323, 0x302, 0x306, 0x31B]
    lines = []
    for i in range(800):
        n = rnd.randint(1, 6)
        cps = []
        for _ in range(n):
            r = rnd.random()
            if r < 0.3:
                cps.append(ord(rnd.choice(viet + viet.upper())))
                for _ in range(rnd.randint(0, 2)):
                    cps.append(rnd.choice(marks))
            elif r < 0.4:
                cps.append(0x3A3)  # Σ (Final_Sigma)
            else:
                cps.append(rnd.choice(rnd.choice(pools)))
        s = "".join(chr(c) for c in cps)
        def hx(t):
            return " ".join(f"{ord(c):X}" for c in t)
        lines.append("|".join([hx(s), hx(ud.normalize("NFC", s)), hx(ud.normalize("NFD", s)),
                               hx(s.upper()), hx(s.lower())]))
    with open(SAMPLE, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"# GENERATED by tools/gen_unicode.py (Unicode {ud.unidata_version}): input|NFC|NFD|upper|lower\n")
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
    sample()
